// Generated by `python -m scripts.audio_contract_codegen` from
// python/backend/room/voice_protocol.py and timing_policy.py. Do not edit by hand:
// python/tests/test_audio_contract.py fails while this file is out of date.
#pragma once

#include <cstdint>

namespace room_audio_contract {
inline constexpr std::uint32_t VoiceSampleRateHz = 48000U;
inline constexpr std::uint32_t VoicePacketFrames = 120U;
inline constexpr double CollectionBudgetMilliseconds = 8.0;
inline constexpr double NoIngressBudgetMilliseconds = 10.0;
inline constexpr double RelaySendPacingMilliseconds = 1.0;
inline constexpr double FallbackReturnReserveMilliseconds = 10.0;
inline constexpr std::uint32_t ReturnCalibrationPackets = 800U;
} // namespace room_audio_contract
