"""
Writes the C++ view of the room audio contract (AudioService and the Native Voice Relay) from the
Python definitions, so the voice protocol and the timing policy have one source.

Run from the `python` folder after changing `voice_protocol.py` or `timing_policy.py`:

    python -m scripts.audio_contract_codegen

`tests/test_audio_contract.py` fails while the committed header differs from what this renders.
"""

from __future__ import annotations

from pathlib import Path

from backend.room.timing_policy import ROOM_TIMING
from backend.room.voice_protocol import VOICE_PACKET_FRAMES, VOICE_SAMPLE_RATE_HZ

HEADER = Path(__file__).resolve().parents[2] / "AudioService" / "src" / "network" / "RoomAudioContract.hpp"


def render() -> str:
    policy = ROOM_TIMING
    constants = (
        ("std::uint32_t", "VoiceSampleRateHz", f"{VOICE_SAMPLE_RATE_HZ}U"),
        ("std::uint32_t", "VoicePacketFrames", f"{VOICE_PACKET_FRAMES}U"),
        ("double", "CollectionBudgetMilliseconds", repr(policy.collection_budget_ms)),
        ("double", "NoIngressBudgetMilliseconds", repr(policy.no_ingress_budget_ms)),
        (
            "double",
            "ConversationCollectionBudgetMilliseconds",
            repr(policy.conversation_collection_budget_ms),
        ),
        (
            "double",
            "ConversationNoIngressBudgetMilliseconds",
            repr(policy.conversation_no_ingress_budget_ms),
        ),
        ("double", "MaximumLiveDelayMilliseconds", repr(policy.maximum_room_delay_ms)),
        ("double", "RelaySendPacingMilliseconds", repr(policy.relay_send_pacing_ms)),
        (
            "double",
            "FallbackReturnReserveMilliseconds",
            repr(policy.return_requirement.fallback_ms),
        ),
        (
            "std::uint32_t",
            "ReturnCalibrationPackets",
            f"{policy.return_requirement.calibration_packets}U",
        ),
    )
    lines = [
        "// Generated by `python -m scripts.audio_contract_codegen` from",
        "// python/backend/room/voice_protocol.py and timing_policy.py. Do not edit by hand:",
        "// python/tests/test_audio_contract.py fails while this file is out of date.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace room_audio_contract {",
        *(f"inline constexpr {kind} {name} = {value};" for kind, name, value in constants),
        "} // namespace room_audio_contract",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    HEADER.write_text(render(), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
