from __future__ import annotations

from datetime import datetime
from typing import Protocol

from backend.social.domain import Account, FriendRequest, Notice, NoticeKind, RoomInvite, Visit


class ChangeNotifier(Protocol):
    """Tells the open apps of these accounts that something they show has changed."""

    def changed(self, account_ids: tuple[str, ...]) -> None: ...


class AccountStore(Protocol):
    def by_device(self, device_key: str) -> Account | None: ...

    def by_id(self, account_id: str) -> Account | None: ...

    def by_ids(self, account_ids: tuple[str, ...]) -> tuple[Account, ...]: ...

    def by_friend_code(self, friend_code: str) -> Account | None: ...

    def by_transfer_code(self, transfer_code: str) -> Account | None: ...

    def add(self, account: Account, device_key: str) -> None: ...

    def save(self, account: Account) -> None: ...

    def move_device(self, device_key: str, account_id: str) -> None: ...

    def set_avatar(self, account_id: str, mime: str, data: bytes) -> None: ...

    def clear_avatar(self, account_id: str) -> None: ...

    def avatar(self, account_id: str) -> tuple[str, bytes] | None: ...

    def map_participant(self, participant_id: str, account_id: str) -> None: ...

    def accounts_of_participants(self, participant_ids: tuple[str, ...]) -> dict[str, str]: ...


class FriendStore(Protocol):
    def friend_ids(self, account_id: str) -> tuple[str, ...]: ...

    def are_friends(self, first: str, second: str) -> bool: ...

    def befriend(self, first: str, second: str, at: datetime) -> None: ...

    def unfriend(self, first: str, second: str) -> None: ...

    def request(self, from_id: str, to_id: str) -> FriendRequest | None: ...

    def add_request(self, request: FriendRequest) -> None: ...

    def remove_request(self, from_id: str, to_id: str) -> None: ...

    def requests_to(self, account_id: str) -> tuple[FriendRequest, ...]: ...

    def requests_from(self, account_id: str) -> tuple[FriendRequest, ...]: ...


class EventStore(Protocol):
    def add_invite(self, invite: RoomInvite) -> None: ...

    def invite(self, invite_id: str) -> RoomInvite | None: ...

    def save_invite(self, invite: RoomInvite) -> None: ...

    def pending_invites_to(self, account_id: str) -> tuple[RoomInvite, ...]: ...

    def pending_invites_into(self, room_id: str) -> tuple[RoomInvite, ...]: ...

    def pending_invite(self, from_id: str, to_id: str, room_id: str) -> RoomInvite | None: ...

    def add_notice(
        self, account_id: str, kind: NoticeKind, other_id: str, room_id: str | None, at: datetime
    ) -> None: ...

    def take_notices(self, account_id: str) -> tuple[Notice, ...]: ...


class VisitStore(Protocol):
    def open_participants(self, room_id: str) -> tuple[str, ...]: ...

    def open_visit(self, visit: Visit) -> None: ...

    def close_visits(
        self, room_id: str, participant_ids: tuple[str, ...], at: datetime
    ) -> None: ...

    def claim_visits(self, participant_id: str, account_id: str) -> None: ...

    def recent_room_ids(self, account_id: str, limit: int) -> tuple[str, ...]: ...

    def visits_in(self, room_ids: tuple[str, ...]) -> tuple[Visit, ...]: ...
