from __future__ import annotations

from pathlib import Path
from typing import Mapping, Protocol


class StorageSystem(Protocol):
    def initialize(self) -> None: ...

    def free_bytes(self, path: Path) -> int: ...

    def usage(self) -> Mapping[str, int]: ...

    def require_free(self, path: Path, required_bytes: int) -> None: ...

    def cleanup_temp(self, max_age_seconds: int) -> int: ...

    def clear_cache(self) -> int: ...


class ModelStorage(Protocol):
    def temporary_path(self, model_id: str, version: str) -> Path: ...

    def final_path(self, model_id: str, version: str) -> Path: ...

    def publish(self, temporary: Path, final: Path) -> None: ...

    def delete(self, path: Path) -> None: ...


class WorkStorage(Protocol):
    def allocate(self, prefix: str) -> Path: ...

    def cleanup(self, path: Path) -> None: ...
